// Code generated by spec/gen from spec/registry.yaml. DO NOT EDIT.
//
// The published attribute vocabulary, as the TypeScript lanes speak it
// (issue #5 §3.2: analysis/ depends on its own math and the published
// attribute vocabulary; render/ depends on analysis/ and published
// contracts). These are the keys and nothing else -- no checker, no
// validation, no reader. A lane that wants to know what a key means
// reads docs/semconv/REGISTRY.md, which is cut from the same spec.

/** The namespace every governed key carries. */
export const NAMESPACE = "atlas.";

/** The conventions version a bundle declares in its manifest. */
export const CONVENTIONS_VERSION = 2;

/**
 * `collection`, stable. What shape of thing the collection holds. Declared
 * once per collection; every feature in it is that kind, and readers pick
 * rendering and UX by this key instead of sniffing geometry types.
 */
export const KEY_GEOMETRY_KIND = "atlas.geometry.kind";

/**
 * `collection`, experimental. Whether an area collection's features wear
 * their names on the map always, or quietly — only on highlight, selection,
 * or an explicit reveal. Area collections only; absent means `always` for
 * areas, and paths are always quiet.
 */
export const KEY_LABEL_POLICY = "atlas.label.policy";

/**
 * `collection`, stable. How a point collection's features draw: markers, or
 * floating text labels. Absent means `pin`; no payload carries a
 * display-type field, and only ingestion still reads one to speak this key
 * for old captures.
 */
export const KEY_RENDER_AS = "atlas.render.as";

/**
 * `collection`, stable. Standard-library icon for a collection without
 * artwork. Resolved to embedded bytes at build time; a reader only sees the
 * resolved asset.
 */
export const KEY_ICON_STD = "atlas.icon.std";

/**
 * `collection`, stable. Whether the icon asset is a monochrome glyph the
 * reader tints, or a picture drawn as-is. Names what a file suffix used to
 * imply.
 */
export const KEY_ICON_KIND = "atlas.icon.kind";

/**
 * `world`, stable. The rim a world's markers wear to stay legible against
 * its art.
 */
export const KEY_ICON_OUTSET = "atlas.icon.outset";

/** `world`, stable. What the raster pictures. Absent means `plane`. */
export const KEY_GEOMETRY_SURFACE = "atlas.geometry.surface";

/**
 * `world`, stable. How a sphere was flattened. Required when surface is
 * `sphere`.
 */
export const KEY_GEOMETRY_PROJECTION = "atlas.geometry.projection";

/** `world`, stable. The raster window the projection fills. */
export const KEY_GEOMETRY_EQUIRECT_PX = "atlas.geometry.equirect.px";

/** `world`, stable. The ground that window pictures. */
export const KEY_GEOMETRY_EQUIRECT_DEG = "atlas.geometry.equirect.deg";

/**
 * `world`, experimental. The raster window a Web-Mercator cut fills. Where
 * `equirect` declares y linear in degrees, `mercator` declares y linear in
 * projected latitude — `asinh(tan lat)` — the flattening a real-world tile
 * window actually is.
 */
export const KEY_GEOMETRY_MERCATOR_PX = "atlas.geometry.mercator.px";

/**
 * `world`, experimental. The ground the Mercator window pictures, in degrees
 * at its edges.
 */
export const KEY_GEOMETRY_MERCATOR_DEG = "atlas.geometry.mercator.deg";

/** `world`, experimental. The body pictured. */
export const KEY_GEOMETRY_BODY = "atlas.geometry.body";

/** `world`, experimental. The body's mean radius. */
export const KEY_GEOMETRY_RADIUS_KM = "atlas.geometry.radius_km";

/**
 * `feature`, experimental. True planetary latitude as published
 * (planetocentric). Provenance and card material; rendering derives from the
 * world-level mapping.
 */
export const KEY_GEO_LAT = "atlas.geo.lat";

/**
 * `feature`, experimental. True planetary longitude as published
 * (east-positive).
 */
export const KEY_GEO_LON = "atlas.geo.lon";

/**
 * `feature`, experimental. The USGS twelve-digit hydrologic unit — the
 * subwatershed — the feature's ground lies wholly within, from the national
 * Watershed Boundary Dataset. A feature spanning subwatersheds carries no
 * key rather than a misleading one.
 */
export const KEY_HYDRO_HUC12 = "atlas.hydro.huc12";

/**
 * `collection`, experimental. The ground width of a path collection's
 * features: a trail is a line and a weight, and the weight lets a reader
 * draw the path as one continuous stroke.
 */
export const KEY_STROKE_WIDTH_PX = "atlas.stroke.width_px";

/**
 * `collection`, experimental. A collection's merge identity across sources.
 * Absent, the icon key stands in.
 */
export const KEY_COLLECTION_KEY = "atlas.collection.key";
