export const state = {
  catalog: null,
  game: null,
  map: null,
  variant: null,
  engine: null,
  projection: null,
  layers: null,
  sources: null,
  hiddenCategories: new Set(),
  collapsedSections: new Set(),
  pins: [],
  pinByID: new Map(),
  selectedPin: null,
  hoveredPin: null,
  labelsHeld: false,
  gridEnabled: false,
  // Whether the cells are drawn, which is a separate question from whether one
  // of them is holding the map to a place.
  subgridVisible: true,
  gridPrefix: "",
  zonesVisible: true,
  zoneRecords: new Map(),
  highlightedZones: new Set(),
  focusedZoneID: null,
  search: "",
  fitZoom: 0,
  zoneTitleCount: 0,
  eligibleLocations: 0,
  tileRun: 0,
  tileStats: { requested: 0, loaded: 0, errors: 0, peakPending: 0 },
  overviewRun: 0,
  overviewKey: "",
  overviewPointer: null,
  overviewDocked: false,
  dockFolded: true,
  // Whether the reader has put the panel away themselves. Until they have, it
  // comes out on its own the first time there is something in it to read.
  dockDismissed: false,
  renderedShard: 0,
  mapRun: 0,
  textByMap: new Map(),
  restore: null,
  settling: false,
  styleCache: new Map(),
  markerIcons: new Map(),
};
